### ISSUE TITLE
Adding scss

### ISSUE THREAD

**Issue by newcraftdev** [CreateSean/craft-starter#1]
Hey,

First of all, I building my first project with this starter and its going great! The only thing I'm missing is the use of scss. For some occasions Tailwind doesn't to the trick, and on those occasions scss would be a great plus. Using imports, functions and for sure, nesting classes would come in handy. 

My webpack knowledge, however, is close to none.. wondering if this is something that can be added in a next release?

**Comment by CreateSean** [comment]
@newcraftdev 

Glad you like this. I'm likely not going to add SASS at all. Since moving to tailwind I find that I write very little css so there is no need to use SASS and I'd rather keep the build process as simple as possible.

I recommend trying to use tailwind for 90-95% of your styling, adding in custom config where necessary. In the end you will write so little css that you won't need sass anymore.
